env:
  global:
    - CC_TEST_REPORTER_ID=714e09c18476dea68cb8446ced07aa9955f5f6c1c211273e4d978db062377525

language: node_js
node_js: "8"
cache: yarn

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - echo "npm test temporarily disabled"
  - npm run test:ci
  - npm run build

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_deploy:
  - cd dist/kalidea/kaligraphi

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
